name: Publish lib
on:
  push:
    branches:
      - master
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn install
      - run: |
          git config --global user.email "rodrigo.passos25@gmail.com"
          git config --global user.name "Rodrigo Passos"
          yarn release
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
